[package]
name = "lichess-board-api-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozy-chess = "0.3.1"
oauth2 = "4.3.0"
reqwest = "0.11.14"
